### PR TITLE
Fix excessive dots in SOA and NS records

### PR DESCRIPTION
**Pull request by gadall**
Address https://github.com/pacoorozco/probind/issues/142

### CODE REVIEW

**Comment by pacoorozco** [comment]
Hi @gadall 
First of all, thanks a lot for your PRs... some of these improvements were already addressed while working on #121 (see `issue-121` branch). 
Maybe, you can test this branch which would be promoted soon as the default one (freezing the current main that is based on Laravel 6.x).

**Comment by gadall** [comment]
@pacoorozco Aha, OK. I was assuming a non-default branch is a feature branch to be merged in.

Perhaps we can have a more general discussion here about what I'm doing.

1. In ProBINDPushZones::generateZoneFileForZone we can invoke bind's named-checkzone or knot's kzonecheck (not requiring the actual DNS server to be installed) before we return success. The exact command should be configurable in global settings.
2. The SFTP stuff should be broken out into various possible implementations of the actual push method.
3. I'm using knot's generated catalog zone. My local config file template simpy contains the zone definitions, included in from the main knot config file.
4. It would be useful to have an optional "template" string configurable per zone. By referencing a template, different zones can behave differently (for example, some with DNSSEC and some without). All probind needs to worry about is the template name.
5. I'm only doing 'knotc reload' (followed by 'knotc zone-reload catz.' due to a minor bug already fixed upstream) on the local knot server. Probind "servers" exist only for the NS record. Probind does not need to worry about contacting slaves. Overall I find this setup quite convenient and flexible.
6. We can also do BIND's catalog zone, which would be generated by probind in the push phase, accomplishing pretty much the same.
7. The import function seems to always create a serial of 0 (zero). Since probind isn't pushing the actual zones to each slave, this can be a problem.

So, how much of this would be of interest to you?

**Comment by gadall** [comment]
@pacoorozco OK, well, I've looked at the 1.x branch and I find that practically everything is not working. I wasn't able to get far enough to check if any one of the issues fixed in my PRs is present in this branch

**Comment by pacoorozco** [comment]
For that specific PR, see my comment [here](https://github.com/pacoorozco/probind/issues/142#issuecomment-959833082)

**Pull request closed without merging**
